#!/bin/bash

BRIGHTNESS_FILE=~/.brightness

if [ ! -f "$BRIGHTNESS_FILE" ]; then
  echo 0 > "$BRIGHTNESS_FILE"
fi

CURRENT_BRIGHTNESS=$(cat "$BRIGHTNESS_FILE")
NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS + 10000))

if [ $NEW_BRIGHTNESS -gt 65535 ]; then
  NEW_BRIGHTNESS=65535
fi

xbrightness $NEW_BRIGHTNESS
echo $NEW_BRIGHTNESS > "$BRIGHTNESS_FILE"
